pipeline:
  identifier: Build_thanhtung1512_harness_cd_pipeline_sample_1712215039615
  name: Build harness-cd-pipeline-sample
  orgIdentifier: default
  projectIdentifier: Onboarding_Project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1712214886660
        repoName: thanhtung1512/harness-cd-pipeline-sample
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
          platform:
            arch: Arm64
            os: MacOS
          runtime:
            spec: {}
            type: Docker
        type: CI
